[package]
name = "client"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Terah <terah.dev@gmail.com>"]

[dependencies]
common = { path = "../common" }
region = { path = "../region" }
log = "0.4"
vek = "0.9"
parking_lot = {version = "0.6", features = ["nightly"]}
