[package]
name = "world"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[profile.dev]

[profile.release]
debug = true

[dependencies]
region = { path = "../region" }
noise = "0.5.1"
euler = "0.3.0"
