[package]
name = "world"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[dependencies]
common = { path = "../common" }
noise = "0.5"
vek = "0.9"
dot_vox = "1.0"
num-traits = "0.2"
