[package]
name = "server"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Terah <terah.dev@gmail.com>"]

[dependencies]
common = { path = "../common" }
world = { path = "../world" }
#log = "0.4"
#pretty_env_logger = "0.2.3"
#time = "0.1.40"

vek = "0.9.5"
specs = "0.12"
parking_lot = "0.6"

# TOML Config files
#toml = "0.4"
#serde = "1.0"
#serde_derive = "1.0"
