[package]
name = "voxygen"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[dependencies]
common = { path = "../common" }
client = { path = "../client" }
region = { path = "../region" }
gfx = "0.17.1"
gfx_window_glutin = "0.24.0"
gfx_device_gl = "0.15.0"
glutin = "0.16.0"
get_if_addrs = "0.5.2"
enum-map = "0.2.31"
nalgebra = "0.15.1"
time = "0.1.40"
coord = "0.11.0"
log = "0.4.1"
pretty_env_logger = "0.2.3"
dot_vox = "1.0.1"
conrod = { git = "https://github.com/veloren/conrod", features = ["gfx_rs"] }
toml = "0.4.6"
serde = "1.0"
serde_derive = "1.0"
